language: python

matrix:
    include:
        - python: 3.6
          dist: trusty
        - python: 3.7
          dist: xenial

# command to install dependencies
install:
  - "pip install poetry"
  - "poetry install"

# command to run tests
script: "poetry run pytest"
